apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hacbs-jvm-operator
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - jvmbuildservice.io
    resources:
      - artifactbuilds
      - artifactbuilds/status
      - dependencybuilds
      - dependencybuilds/status
      - rebuiltartifacts
      - rebuiltartifacts/status
      - systemconfigs
      - systemconfigs/status
      - jbsconfigs
      - jbsconfigs/status
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - quota.openshift.io
    resources:
      - clusterresourcequotas
    verbs:
      - get
      - list
      - watch

  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get

  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineruns/status
      - taskruns
      - taskruns/status
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ''
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - create
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    resourceNames:
      - jvm-build-workspace-artifact-cache
    verbs:
      - patch
      - delete
  - apiGroups:
      - ""
    # note - tekton gives its controller read access to secrets, so any pods there can access secrets in the pods namespace
    resources:
      - secrets
    resourceNames:
      - jvm-build-image-secrets
      - jvm-build-git-secrets
    verbs:
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    # note - tekton gives its controller read access to secrets, so any pods there can access secrets in the pods namespace
    resources:
      - secrets
    verbs:
      - get
      - create
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
    - "apps"
    resources:
      - deployments
    resourceNames:
      - jvm-build-workspace-artifact-cache
    verbs:
      - delete
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - jvm-build-tls-ca
    verbs:
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - create
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    resourceNames:
      - jvm-build-workspace-artifact-cache
    verbs:
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - create
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    resourceNames:
      - jvm-build-workspace-artifact-cache
    verbs:
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - resourcequotas
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - rolebindings
    verbs:
      - get
      - create
      - list
      - watch
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - rolebindings
    resourceNames:
      - jvm-build-workspace-artifact-cache
    verbs:
      - patch
      - delete
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - imagerepositories
    verbs:
      - create
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hacbs-jvm-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hacbs-jvm-operator
subjects:
  - kind: ServiceAccount
    name: hacbs-jvm-operator
    namespace: jvm-build-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hacbs-jvm-operator-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - jvmbuildservice.io
    resources:
      - artifactbuilds
      - artifactbuilds/status
      - dependencybuilds
      - dependencybuilds/status
      - systemconfigs
      - systemconfigs/status
      - jbsconfigs
      - jbsconfigs/status
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hacbs-jvm-cache
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - jvmbuildservice.io
    resources:
      - rebuiltartifacts
      - artifactbuilds
      - dependencybuilds
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - jvmbuildservice.io
    resources:
      - artifactbuilds/status
    verbs:
      - patch
      - update
  - apiGroups:
      - jvmbuildservice.io
    resources:
      - artifactbuilds
    verbs:
      - patch
      - update
  - apiGroups:
      - jvmbuildservice.io
    resources:
      - jbsconfigs
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - tekton.dev
    resources:
      - taskruns
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - taskruns/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
