---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven-deployment
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: image-build, konflux
  labels:
    app.kubernetes.io/version: "0.1"
    build.appstudio.redhat.com/build_type: docker
spec:
  description: |-
    Takes a OCI archive and deploys the result
  params:
    - name: ORAS_OPTIONS
      type: string
      description: Optional environment variable string for build-trusted-artifacts
      default: ""
    - name: IMAGE_URL
      description: Reference to the OCI archive
      type: string
    - name: IMAGE_DIGEST
      description: Digest to use
      type: string
    - name: PRE_BUILD_IMAGE_DIGEST
      description: PreBuilddDigest to use
      type: string
    - name: MVN_REPO
      description: Maven repository to deploy to
      type: string
    - name: MVN_USERNAME
      description: Maven repository username
      type: string
    - name: MVN_PASSWORD
      description: Name of the secret holding the Maven repository password
      type: string
  volumes:
    - name: shared
      emptyDir: {}
    - name: workdir
      emptyDir: {}
  stepTemplate:
    volumeMounts:
      - mountPath: /shared
        name: shared
      - mountPath: /var/workdir
        name: workdir
  steps:
    - name: restore-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:d6f57d97d19008437680190908fe5444cda380f9c77d0e9efde7153720412e05
      script: |
        set -x
        echo "Restoring artifacts and source to workspace"
        use-archive $PRE_BUILD_IMAGE_DIGEST=/var/workdir/source
        URL=$IMAGE_URL
        DIGEST=$IMAGE_DIGEST
        AARCHIVE=$(oras manifest fetch $ORAS_OPTIONS $URL@$DIGEST | jq --raw-output '.layers[0].digest')
        echo "URL $URL DIGEST $DIGEST AARCHIVE $AARCHIVE"
        use-archive oci:$URL@$AARCHIVE=/var/workdir/artifacts
        ls -lR /var/workdir
      env:
        - name: ORAS_OPTIONS
          value: $(params.ORAS_OPTIONS)
        - name: IMAGE_DIGEST
          value: $(params.IMAGE_DIGEST)
        - name: IMAGE_URL
          value: $(params.IMAGE_URL)
        - name: PRE_BUILD_IMAGE_DIGEST
          value: $(params.PRE_BUILD_IMAGE_DIGEST)
    - name: deploy
      image: quay.io/ncross/hacbs-jvm-build-request-processor:dev
      securityContext:
        runAsUser: 0
      computeResources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: 50m
          memory: 512Mi
      env:
        - name: MAVEN_OPTS
          value: "-Dmaven.wagon.http.ssl.insecure=true"
        - name: MVN_REPO
          value: $(params.MVN_REPO)
        - name: MVN_USERNAME
          value: $(params.MVN_USERNAME)
        - name: MAVEN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.MVN_PASSWORD)
              key: mavenpassword
        - name: SSL_CERT_DIR
          value: /tekton-custom-certs:/etc/ssl/certs:/etc/pki/tls/certs
      args:
        - deploy
        - --directory=/var/workdir/artifacts
        - --mvn-repo=$(params.MVN_REPO)
        - --mvn-username=$(params.MVN_USERNAME)
